// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAbigT56UtSHdu5cHZvn767EkVkSu_FFk',
    appId: '1:835391927105:web:e0d362d3bf0d1d53e327c0',
    messagingSenderId: '835391927105',
    projectId: 'mobilelabsastu',
    authDomain: 'mobilelabsastu.firebaseapp.com',
    storageBucket: 'mobilelabsastu.appspot.com',
    measurementId: 'G-B33GSY82Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3c0s1jrTu255NopSaFmt4aoAMvVY-Zs',
    appId: '1:835391927105:android:d00d4456a6960e46e327c0',
    messagingSenderId: '835391927105',
    projectId: 'mobilelabsastu',
    storageBucket: 'mobilelabsastu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUak8FsauDA193bE7bZIHOD7NmCGqLpwY',
    appId: '1:835391927105:ios:760ae9f92d8afedfe327c0',
    messagingSenderId: '835391927105',
    projectId: 'mobilelabsastu',
    storageBucket: 'mobilelabsastu.appspot.com',
    iosClientId: '835391927105-rtfdkv051dbs7hkppd724qg1jbmc9i6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUak8FsauDA193bE7bZIHOD7NmCGqLpwY',
    appId: '1:835391927105:ios:760ae9f92d8afedfe327c0',
    messagingSenderId: '835391927105',
    projectId: 'mobilelabsastu',
    storageBucket: 'mobilelabsastu.appspot.com',
    iosClientId: '835391927105-rtfdkv051dbs7hkppd724qg1jbmc9i6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
}
